source 'https://rubygems.org'

gem "middleman", "~> 3.0.13"

# Unsatisfied dependency before?
gem 'rb-inotify', '~> 0.9'

# Live reloading on source change
gem "middleman-livereload"

# Blogging extension
gem "middleman-blog"

# Templating engine
gem "slim"

# Compass plugins
gem 'susy', "~> 1.0.8" # Susy
gem 'compass-h5bp', "~> 0.1.0" # HTML5 Boilerplate styles

